export const GET_BOARDS = 'GET_BOARDS';
export const ADD_BOARD = 'ADD_BOARD';
export const DELETE_BOARD = 'DELETE_BOARD';
export const BOARDS_LOADING = 'BOARDS_LOADING';
export const CLEAR_BOARDS = 'CLEAR_BOARDS';

export const GET_ONE_BOARD = 'GET_ONE_BOARD';
export const ONE_BOARD_LOADING = 'ONE_BOARD_LOADING';
export const GET_ONE_BOARD_ERROR = 'GET_ONE_BOARD_ERROR';

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';